### PR TITLE
Fix workflows

### PR DESCRIPTION
**Pull request by snapdgn**
partial fix for : #22

### CODE REVIEW

**Comment by ThinkOpenly** [comment]
Nitish, could you describe what this PR is about?

**Comment by ThinkOpenly** [comment]
Also, are you intending the commit from PR #23 to appear hear, too? If not, you need to base this one on that one. If they are basically under the same umbrella, you could just combine them into a single PR.

**Comment by snapdgn** [comment]
This PR fixes the `build` workflows. 

> Also, are you intending the commit from PR #23 to appear hear, too?

I didn't, primary reason build workflow was not working was due to the absence of `sail_json_backend.opam` file. 

Once the file was added, the build worked for newer version `5.0.0` but failed for the older versions.
That's the reason i separated them. 

But, given that both were the causes of the build failure, should I consolidate them into a single PR?

**Comment by ThinkOpenly** [comment]
> should I consolidate them into a single PR?

That sounds like a good plan. Thanks!

**Comment by snapdgn** [comment]
@ThinkOpenly, this resolves the workflow issues. I haven't included support for earlier versions at this time(only `5.0.0`) . I'll address that in a separate PR when I have more time to dedicate to it. My priority was to get this functioning as quickly as possible.

**Review by ThinkOpenly — APPROVED** [review]

**Comment by ThinkOpenly** [comment]
Thanks, @snapdgn !! Really appreciate the effort in addressing things that are too easily ignored!

**Pull request merged**
