### PR TITLE
Ci for json validation

### LINKED ISSUE #30: Need an action that validates that emitted JSON is at least valid syntax

### PR DESCRIPTION
**Pull request by snapdgn**
Potential Fix: #30

### CODE REVIEW

**Comment by snapdgn** [comment]
@ThinkOpenly, this should be done now.
Initially I was working on writing a different workflow(file) for this with two different approaches. One involved building/installing `sail` again and then validating, which was adding up to the cost of resources, and another transferring build artifacts over from `build.yml` to the new `validate-json`, and there was this whole issue of setting up ocaml/sail properly.

So I went with the simplest approach and added a new run in the same `build` workflow, which runs just after the install step. I've tested it against my own repo and it works.

Note:
- I removed the (`etc/ci_core_tests.sh`) from sail, since we don't rely on testing now. Let me know if i should add this.
- This depends on: https://github.com/ThinkOpenly/sail-riscv/pull/28 (this PR needs to be merged first).

**Comment by ThinkOpenly** [comment]
https://github.com/ThinkOpenly/sail-riscv/pull/28 is now merged. I've restarted the failed jobs here. :crossed_fingers:

**Comment by ThinkOpenly** [comment]
> * I removed the (`etc/ci_core_tests.sh`) from sail, since we don't rely on testing now. Let me know if i should add this.

How strongly do you feel about this? Previous runs have been on the order of a couple of minutes. I'm inclined to leave it in.

**Comment by snapdgn** [comment]
> > * I removed the (`etc/ci_core_tests.sh`) from sail, since we don't rely on testing now. Let me know if i should add this.
> 
> How strongly do you feel about this? Previous runs have been on the order of a couple of minutes. I'm inclined to leave it in.

Honestly not much, it adds maybe couple seconds to a minute. I believe we can afford it.  I've added the tests back.

P.S: ~ 2 minutes
image

**Pull request merged**
